# Generated by Django 5.2.4 on 2025-07-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="completed",
            new_name="is_completed",
        ),
        migrations.AddField(
            model_name="task",
            name="reminder",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
